name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main  # You can specify your main branch name here

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry (GHCR)
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and tag Docker image
        run: |
          docker buildx create --use
          docker buildx build --push --tag ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest .

      - name: Cleanup
        run: docker buildx stop
